### ISSUE TITLE
Some intent-to posts are being missed

### ISSUE THREAD

**Issue by saschanaz** [autonome/intenttoship-bot#11]
For example, https://groups.google.com/a/mozilla.org/g/dev-platform/c/3g0fnn6682A is missed while https://groups.google.com/a/mozilla.org/g/dev-platform/c/ysU5Q-uVhlk is on the bot: https://botsin.space/@intenttoship/110547325569815101

I thought it was because the former was using "intent to implement" but per the current code it seemingly just matches with all "intent to" titles, so I'm not sure what happened there.

**Comment by autonome** [comment]
Hmm i've since updated how it works, and the spottiness w/ both the custom back-end i wrote and IFTTT should be gone now w/ the Zapier approach.
