### ISSUE TITLE
Posts on Mastodon incomplete

### ISSUE THREAD

**Issue by Schweinepriester** [autonome/intenttoship-bot#14]
Heyhey,

thanks for creating and maintaining this!

It would appear that the posts on Mastodon are incomplete, at least missing the URL.

Example: https://botsin.space/@intenttoship/113393295168089430

**Comment by justbearcause** [comment]
Same problem on Twitter

**Comment by Schweinepriester** [comment]
bump @autonome 0:-)

**Comment by autonome** [comment]
Thanks for filing, sorry for delay. See thread here https://bsky.app/profile/burrito.space/post/3laattpr3yg2d
