### ISSUE TITLE
Should escape HTML entitities from email titles?

### ISSUE THREAD

**Issue by emilio** [autonome/intenttoship-bot#3]
Just a guess, https://twitter.com/intenttoship/status/928413242682167297 should read:

> Intent to unship: &lt;a&gt; as &lt;area&gt; in image maps 

Thanks for the bot, it's quite nice! :)

**Comment by mozfreddyb** [comment]
Just stumbled upon the same thing. I'm not 100% sure where to patch this, but maybe `item.title` in line 21 and following (for each browser's feed) would be a good start.

Will you accept a pull request that does this, @autonome? :)

**Comment by autonome** [comment]
Hey @mozfreddyb! YES, I would love to accept a PR for this.

**Comment by mozfreddyb** [comment]
Clearly this didn't work :| https://twitter.com/intenttoship/status/1139490687609638912

**Comment by mozfreddyb** [comment]
> Clearly this didn't work :| https://twitter.com/intenttoship/status/1139490687609638912

Before I revisit, did you restart the bot after #4 was merged?

**Comment by mozfreddyb** [comment]
> > Clearly this didn't work :| https://twitter.com/intenttoship/status/1139490687609638912
> 
> Before I revisit, did you restart the bot after #4 was merged?

@autonome?

**Comment by autonome** [comment]
Yep, I imported the changes at the time to the Glitch, which is restarted a few times per day (cron-job.org vs Glitch dance).

https://glitch.com/edit/#!/intent-to-ship-bot?path=index.js:1:0

**Comment by autonome** [comment]
Work for next attempt at fix in #5.
