### ISSUE TITLE
Removing the Edge platform status feed

### ISSUE THREAD

**Issue by captainbrosset** [autonome/intenttoship-bot#9]
Unfortunately Microsoft Edge has not been keeping its platform status page up to date ever since we moved to Chromium. So this feed is essentially dead/incorrect: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/rss/ and should probably be removed from your bot.

The platform features that are implemented by the Edge team are almost always contributed upstream to Chromium, so the blink dev mailing list is probably the right place to get the information anyway.

**Comment by autonome** [comment]
Thanks, removed!
